### ISSUE TITLE
PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by huchunjun425** [codeslake/PVDNet#11]
File "run.py", line 277, in <module>
    config_lib.log_config(config.LOG_DIR.config, config)
  File "E:\code\python\PVDNet\configs\config.py", line 136, in log_config
    with open(path + '/config.txt', 'w') as f:
PermissionError: [Errno 13] Permission denied: 'E:/code/python/PVDNet\\PVDNet_TOG2021\\PVDNet_DVD\\config/config.txt'

**Comment by codeslake** [comment]
Check the permission of the folder.

**Comment by huchunjun425** [comment]
> 
![image](https://user-images.githubusercontent.com/103866259/197429798-aff10228-c545-4b13-bc0a-ed8561a8877a.png)

However, in this directory, the file mentioned in this problem does not exist”config.txt“

**Comment by codeslake** [comment]
It is not the right directory. Check the `PVDNet_TOG2021` folder.

**Comment by huchunjun425** [comment]
ok，thanks.
