### ISSUE TITLE
Some problems about the testing results.

### ISSUE THREAD

**Issue by ljzycmd** [codeslake/PVDNet#2]
Hi, this is a great job! But I have some questions about PVDNet. I have tested PVDNet (normal size version) on DVD and GOPRO with the checkpoint provided, however, the testing results are lower than those in the original paper. Specifically, I got 31.89 PSNR and 0.9236 SSIM on DVD, and 31.09 PSNR and 0.9140 SSIM on GOPRO. So, is there something wrong with the configuration?

**Comment by codeslake** [comment]
Hi, @ljzycmd.

Did you use [provided matlab code](https://github.com/codeslake/PVDNet/tree/main/evaluation)?

**Comment by ljzycmd** [comment]
Ya, I did ignore this! I would try it later. 
Thanks!

**Comment by codeslake** [comment]
No worries!

**Comment by Iverson-zq** [comment]
> Hi, this is a great job! But I have some questions about PVDNet. I have tested PVDNet (normal size version) on DVD and GOPRO with the checkpoint provided, however, the testing results are lower than those in the original paper. Specifically, I got 31.89 PSNR and 0.9236 SSIM on DVD, and 31.09 PSNR and 0.9140 SSIM on GOPRO. So, is there something wrong with the configuration?

Hi,bro. Have you reproduced successfully? Could you tell me the approximate training time of the required model and the hardware environment of your experiment? Sorry, due to my personal hardware environment is limited (single card 1080Tijin12G), so send an email to ask for your advice, look forward to your reply, thank you!

**Comment by ljzycmd** [comment]
Hi, Zhao. I am sorry that I have only tested the PVDNet with the checkpoint provided by the author. When testing under the resolution of 1280 \times 720, PVDNet (normal size) spends 0.28s processing a frame with a NIVIDA 2080Ti (11G). If you want to reproduce these results, it may takes much time of yours to retrain the BIMNet and PVDNet.&nbsp;
&nbsp;


MingdengCao
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 上午10:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [codeslake/PVDNet] Some problems about the testing results. (#2)





  
Hi, this is a great job! But I have some questions about PVDNet. I have tested PVDNet (normal size version) on DVD and GOPRO with the checkpoint provided, however, the testing results are lower than those in the original paper. Specifically, I got 31.89 PSNR and 0.9236 SSIM on DVD, and 31.09 PSNR and 0.9140 SSIM on GOPRO. So, is there something wrong with the configuration?
  
Hi,bro. Have you reproduced successfully? Could you tell me the approximate training time of the required model and the hardware environment of your experiment? Sorry, due to my personal hardware environment is limited (single card 1080Tijin12G), so send an email to ask for your advice, look forward to your reply, thank you!
