### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by Michaelwhite34** [codeslake/PVDNet#4]
(PVDNet) PS D:\PVDNet> python run.py --mode PVDNet_large_nah --config config_PVDNet_large --data random --ckpt_abs_name ckpt/PVDNet_large_nah.pytorch
Laoding Config for evaluation
Traceback (most recent call last):
  File "run.py", line 311, in <module>
    config = config_lib.get_config(args.project, args.mode, args.config)
  File "D:\PVDNet\configs\config_PVDNet_large.py", line 42, in get_config
    IpE = math.ceil((len(list(range(0, total_frame_num - (config.frame_itr_num-1), config.frame_itr_num)))) / actual_batch_size) * config.frame_itr_num
ZeroDivisionError: division by zero

**Comment by codeslake** [comment]
Hi, @Michaelwhite34.

Is Cuda available on your device?

**Comment by Michaelwhite34** [comment]
> Hi, @Michaelwhite34.
> 
> Is Cuda available on your device?

Yes,I have a gtx 1660Ti,by the way it's on windows 10.

**Comment by codeslake** [comment]
I've tried running PyTorch on Windows.
Is `nvidia-smi` available on Windows?
Would you prepend `CUDA_VISIBLE_DEVICES=0` before the command for evaluating PVDNet?

Or, you can just set `IpE=0`. I just put it to check the number of iterations needed for an epoch.

**Comment by Michaelwhite34** [comment]
> I've never tried running PyTorch on Windows. Is `nvidia-smi` available on Windows? Would you prepend `CUDA_VISIBLE_DEVICES=0` before the command for evaluating PVDNet?
> 
> Or, you can just set `IpE=0`. I just put it to check the number of iterations needed for an epoch.

After setting it to 0,(PVDNet) PS D:\PVDNet> python run.py --mode PVDNet_large_nah --config config_PVDNet_large --data random --ckpt_abs_name ckpt/PVDNet_large_nah.pytorch
Laoding Config for evaluation
        Project : PVDNet_TOG2021
        Mode : PVDNet_large_nah
        Config: config_PVDNet_large
        Network: PVDNet_large
        Trainer: trainer
Loading Model...
        initializing deblurring network
Traceback (most recent call last):
  File "run.py", line 341, in <module>
    eval(config)
  File "D:\PVDNet\eval.py", line 198, in eval
    eval_quan_qual(config)
  File "D:\PVDNet\eval.py", line 68, in eval_quan_qual
    blur_folder_path_list, blur_file_path_list, gt_file_path_list = init(config, mode)
  File "D:\PVDNet\eval.py", line 43, in init
    model = create_model(config)
  File "D:\PVDNet\models\__init__.py", line 5, in create_model
    model = lib.Model(config)
  File "D:\PVDNet\models\trainers\trainer.py", line 35, in __init__
    self.network = DeblurNet(config).to(torch.device('cuda'))
  File "D:\PVDNet\models\trainers\trainer.py", line 255, in __init__
    lib = importlib.import_module('models.archs.{}'.format(config.network_BIMNet))
  File "D:\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\PVDNet\models\archs\liteFlowNet.py", line 6, in <module>
    if float(torch.version.cuda) > 10.1:
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by codeslake** [comment]
You will need to find a way to get cuda version in Windows (which is `torch.viersion.cuda` in ubuntu).

**Comment by Michaelwhite34** [comment]
> You will need to find a way to get cuda version in Windows (which is `torch.viersion.cuda` in ubuntu).

nvidia-smi
Sat Jan 22 10:13:20 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.84       Driver Version: 472.84       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   46C    P8     4W /  N/A |    507MiB /  6144MiB |     22%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      7184    C+G   ...b3d8bbwe\WinStore.App.exe    N/A      |
|    0   N/A  N/A      8856    C+G   ...es.TextInput.InputApp.exe    N/A      |
|    0   N/A  N/A     14832    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A     15916    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A     16620    C+G   ...新梦想世界\exe\render.dll    N/A      |
|    0   N/A  N/A     17712    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A     18560    C+G   ...w5n1h2txyewy\SearchUI.exe    N/A      |
|    0   N/A  N/A     22052    C+G   ...lPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A     22272    C+G   Insufficient Permissions        N/A      |
+-----------------------------------------------------------------------------+

**Comment by Michaelwhite34** [comment]
> You will need to find a way to get cuda version in Windows (which is `torch.viersion.cuda` in ubuntu).

nvidia-smi
Sat Jan 22 10:13:20 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.84       Driver Version: 472.84       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   46C    P8     4W /  N/A |    507MiB /  6144MiB |     22%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by Michaelwhite34** [comment]
> 

(PVDNet) PS D:\PVDNet> python run.py --mode PVDNet_large_nah --config config_PVDNet_large --data random --ckpt_abs_name ckpt/PVDNet_large_nah.pytorch
[1m[32mLaoding Config for evaluation[0m
[1m[31m       Project : PVDNet_TOG2021[0m
[1m[31m       Mode : PVDNet_large_nah[0m
[1m[31m       Config: config_PVDNet_large[0m
[1m[31m       Network: PVDNet_large[0m
[1m[31m       Trainer: trainer[0m
[1m[32mLoading Model...[0m
[1m[31m       initializing deblurring network[0m
Warning! No positional inputs found for a module, assuming batch size is 1.
[1m[32mComputing model complexity...[0m
Computational complexity (Macs):   1755.80841016 B
Number of parameters:           23.36178 M

Loading checkpoint 'PVDNet_large_nah.pytorch' on model 'PVDNet_large_nah': <All keys matched successfully>
Traceback (most recent call last):
  File "run.py", line 341, in <module>
    eval(config)
  File "D:\PVDNet\eval.py", line 198, in eval
    eval_quan_qual(config)
  File "D:\PVDNet\eval.py", line 186, in eval_quan_qual
    total_itr_time = total_itr_time / total_norm
ZeroDivisionError: division by zero

**Comment by codeslake** [comment]
That means the evaluation has never gone through a loop. Make sure the test set is in the right place.

**Comment by Michaelwhite34** [comment]
My sequence structure is D:\PVDNet\datasets\video_deblur\random\1\*.png  ...Is this not right ?

**Comment by codeslake** [comment]
I believe it is right. Did you change [data_offset](https://github.com/codeslake/PVDNet/blob/main/configs/config.py#L41)?

**Comment by Michaelwhite34** [comment]
No,should I change it ?

**Comment by Michaelwhite34** [comment]
emm,should I just unmark the line "config.data_offset = 'datasets/video_deblur" ?

**Comment by codeslake** [comment]
Set it to `D:\PVDNet\datasets\video_deblur`.

**Comment by Michaelwhite34** [comment]
(PVDNet) PS D:\PVDNet> python run.py --mode PVDNet_large_nah --config config_PVDNet_large --data random --ckpt_abs_name ckpt/PVDNet_large_nah.pytorch
Traceback (most recent call last):
  File "run.py", line 201, in <module>
    from configs.config import set_train_path
  File "D:\PVDNet\configs\config.py", line 43
    config.data_offset = 'D:/PVDNet/datasets/video_deblur'
    ^

**Comment by codeslake** [comment]
It says indentation error. Check the indentation.

**Comment by Michaelwhite34** [comment]
Still
(PVDNet) PS D:\PVDNet> python run.py --mode PVDNet_large_nah --config config_PVDNet_large --data random --ckpt_abs_name ckpt/PVDNet_large_nah.pytorch
[1m[32mLaoding Config for evaluation[0m
[1m[31m       Project : PVDNet_TOG2021[0m
[1m[31m       Mode : PVDNet_large_nah[0m
[1m[31m       Config: config_PVDNet_large[0m
[1m[31m       Network: PVDNet_large[0m
[1m[31m       Trainer: trainer[0m
[1m[32mLoading Model...[0m
[1m[31m       initializing deblurring network[0m
Warning! No positional inputs found for a module, assuming batch size is 1.
[1m[32mComputing model complexity...[0m
Computational complexity (Macs):   1755.80841016 B
Number of parameters:           23.36178 M

Loading checkpoint 'PVDNet_large_nah.pytorch' on model 'PVDNet_large_nah': <All keys matched successfully>
Traceback (most recent call last):
  File "run.py", line 341, in <module>
    eval(config)
  File "D:\PVDNet\eval.py", line 198, in eval
    eval_quan_qual(config)
  File "D:\PVDNet\eval.py", line 186, in eval_quan_qual
    total_itr_time = total_itr_time / total_norm
ZeroDivisionError: division by zero

**Comment by Michaelwhite34** [comment]
# data dir
    config.data = 'DVD' # 'nah'
   # config.data_offset = '/data1/junyonglee/video_deblur'
    config.data_offset = 'D:\PVDNet\datasets\video_deblur'

**Comment by codeslake** [comment]
Try to use '\' for `data_offset`, not '/'.

I will be out for a few hours. I am pretty sure it is the path problem.

**Comment by Michaelwhite34** [comment]
> Try to use '\' for `data_offset`, not '/'.
> 
> I will be out for a few hours. I am pretty sure it is the path problem.

I am using \ already

**Comment by codeslake** [comment]
> (PVDNet) PS D:\PVDNet> python run.py --mode PVDNet_large_nah --config config_PVDNet_large --data random --ckpt_abs_name ckpt/PVDNet_large_nah.pytorch
> Traceback (most recent call last):
> File "run.py", line 201, in
> from configs.config import set_train_path
> File "D:\PVDNet\configs\config.py", line 43
> config.data_offset = 'D:/PVDNet/datasets/video_deblur'
> ^
> IndentationError: unexpected indent

Here, you are using '/'.

**Comment by Michaelwhite34** [comment]
> > (PVDNet) PS D:\PVDNet> python run.py --mode PVDNet_large_nah --config config_PVDNet_large --data random --ckpt_abs_name ckpt/PVDNet_large_nah.pytorch
> > Traceback (most recent call last):
> > File "run.py", line 201, in
> > from configs.config import set_train_path
> > File "D:\PVDNet\configs\config.py", line 43
> > config.data_offset = 'D:/PVDNet/datasets/video_deblur'
> > ^
> > IndentationError: unexpected indent
> 
> Here, you are using '/'.

I changed after that.

**Comment by Michaelwhite34** [comment]
Do I need to change the line "config.data = 'DVD' # 'nah'"?

**Comment by codeslake** [comment]
> Do I need to change the line "config.data = 'DVD' # 'nah'"?

No, it is given in `python run.py --mode PVDNet_large_nah --config config_PVDNet_large --data random --ckpt_abs_name ckpt/PVDNet_large_nah.pytorch`. Did you get it running?

**Comment by Michaelwhite34** [comment]
> > Do I need to change the line "config.data = 'DVD' # 'nah'"?
> 
> No, it is given in `python run.py --mode PVDNet_large_nah --config config_PVDNet_large --data random --ckpt_abs_name ckpt/PVDNet_large_nah.pytorch`. Did you get it running?

still (PVDNet) PS D:\PVDNet> python run.py --mode PVDNet_large_nah --config config_PVDNet_large --data random --ckpt_abs_name ckpt/PVDNet_large_nah.pytorch
[1m[32mLaoding Config for evaluation[0m
[1m[31m       Project : PVDNet_TOG2021[0m
[1m[31m       Mode : PVDNet_large_nah[0m
[1m[31m       Config: config_PVDNet_large[0m
[1m[31m       Network: PVDNet_large[0m
[1m[31m       Trainer: trainer[0m
[1m[32mLoading Model...[0m
[1m[31m       initializing deblurring network[0m
Warning! No positional inputs found for a module, assuming batch size is 1.
[1m[32mComputing model complexity...[0m
Computational complexity (Macs):   1755.80841016 B
Number of parameters:           23.36178 M

Loading checkpoint 'PVDNet_large_nah.pytorch' on model 'PVDNet_large_nah': <All keys matched successfully>
Traceback (most recent call last):
  File "run.py", line 341, in <module>
    eval(config)
  File "D:\PVDNet\eval.py", line 198, in eval
    eval_quan_qual(config)
  File "D:\PVDNet\eval.py", line 186, in eval_quan_qual
    total_itr_time = total_itr_time / total_norm
ZeroDivisionError: division by zero

**Comment by codeslake** [comment]
Would you replace [this line](https://github.com/codeslake/PVDNet/blob/main/eval.py#58) to the following lines and print out the result?
```
print(config.EVAL.data_path, config.EVAL.input_path)
blur_folder_path_list, blur_file_path_list, _ = load_file_list(config.EVAL.data_path, config.EVAL.input_path)
print(blur_file_path_list)
```

**Comment by Michaelwhite34** [comment]
> Would you replace [this line](https://github.com/codeslake/PVDNet/blob/main/eval.py#58) to the following lines and print out the result?
> 
> ```
> print(config.EVAL.data_path, config.EVAL.input_path)
> blur_folder_path_list, blur_file_path_list, _ = load_file_list(config.EVAL.data_path, config.EVAL.input_path)
> print(blur_file_path_list)
> ```

Got it working,turns out I should use "/"

**Comment by codeslake** [comment]
> Got it working, turns out I should use "/"

Great!

**Comment by Michaelwhite34** [comment]
Can we deal with cuda out of memory?

**Comment by codeslake** [comment]
You may try smaller model *e.g.*, `python run.py --mode PVDNet_nah --config config_PVDNet --data random --ckpt_abs_name ckpt/PVDNet_nah.pytorch`. 
You may also try downsmaple input frames.
