### ISSUE TITLE
Some questions about testing

### ISSUE THREAD

**Issue by wgp666** [codeslake/PVDNet#5]
Hello, can you share the logs file. The code reports an error because the logs file is missing during the test.

**Comment by codeslake** [comment]
Hi, would you share the error message?

**Comment by wgp666** [comment]
I am so sorry! I found out what I did wrong. I used the wrong test command that caused the code to run with an error. It's working now! Thank you so much for sharing!

**Comment by codeslake** [comment]
Good to hear! Closing the issue.
