### ISSUE TITLE
Error training on Windows

### ISSUE THREAD

**Issue by wgp666** [codeslake/PVDNet#7]
Hi, I am getting the following error when I run this code on windows.
Traceback (most recent call last):
  File "run.py", line 295, in <module>
    trainer.train()
  File "run.py", line 69, in train
    self.ckpt_manager.save(self.model.get_network(), self.model.get_training_state(0), 0, score = [1e-8, 1e8])
  File "D:\PVDNet-main\ckpt_manager.py", line 138, in save
    self._update_files()
  File "D:\PVDNet-main\ckpt_manager.py", line 148, in _update_files
    lines_prev = self._sort(lines[:-1])
  File "D:\PVDNet-main\ckpt_manager.py", line 166, in _sort
    scores = [float(score.split(' ')[1]) for score in lines]
  File "D:\PVDNet-main\ckpt_manager.py", line 166, in <listcomp>
    scores = [float(score.split(' ')[1]) for score in lines]
IndexError: list index out of range

**Comment by codeslake** [comment]
What is your `log_offset` (in [here](https://github.com/codeslake/PVDNet/blob/main/configs/config.py#L56))?

**Comment by wgp666** [comment]
> What is your `log_offset` (in [here](https://github.com/codeslake/PVDNet/blob/main/configs/config.py#L56))?

'D:\PVDNet-main\logs'

**Comment by wgp666** [comment]
> What is your `log_offset` (in [here](https://github.com/codeslake/PVDNet/blob/main/configs/config.py#L56))?

log_offset = 'D:\PVDNet-main\logs'

**Comment by codeslake** [comment]
> > What is your `log_offset` (in [here](https://github.com/codeslake/PVDNet/blob/main/configs/config.py#L56))?
> 
> log_offset = 'D:\PVDNet-main\logs'

Does 'D:\PVDNet-main\logs\checkpoint\train\epoch\checkpoints.txt' exist? If it does, would you put the content of the file here?

**Comment by codeslake** [comment]
Will you try to set the `log_offset` to `D:\\PVDNet-main\\logs`? Use `\\` for [`data_offset`](https://github.com/codeslake/PVDNet/blob/main/configs/config.py#L42) also.

**Comment by codeslake** [comment]
> Do you mean the file 'D:\PVDNet-main\logs\PVDNet_TOG2021\PVDNet_DVD\checkpoint\train\epoch\checkpoints.txt'? The contents of the file are shown below. PVDNet_DVD_00000.pytorch 1e-08 100000000.0
> 
> PVDNet_DVD_00000.pytorch 1e-08 100000000.0

Are there two lines? There should only a single line.

**Comment by codeslake** [comment]
Oh, my mistake. Yeah, there should be two lines.
Would you change [this line](https://github.com/codeslake/PVDNet/blob/main/ckpt_manager.py#L166) as follows?
```
        scores = [float(score.split()[1]) for score in lines]
```

**Comment by wgp666** [comment]
> Oh, my mistake. Yeah, there should be two lines. Would you change [this line](https://github.com/codeslake/PVDNet/blob/main/ckpt_manager.py#L166) as follows?
> 
> ```python
>         scores = [float(score.split()[1]) for score in lines]
> ```

I changed it. But still this error is reported, and the file still has two lines.
![image](https://user-images.githubusercontent.com/89969997/163740633-ed888dea-74b1-4d24-9e16-10e71c251f73.png)
![image](https://user-images.githubusercontent.com/89969997/163740673-f7ac1edc-8dae-4615-b1dd-4738a04572f3.png)

**Comment by wgp666** [comment]
> Will you try to set the `log_offset` to `D:\\PVDNet-main\\logs`? Use `\\` for [`data_offset`](https://github.com/codeslake/PVDNet/blob/main/configs/config.py#L42) also.

I just tried it and still this error is reported.

**Comment by codeslake** [comment]
Will you change [this function](https://github.com/codeslake/PVDNet/blob/main/ckpt_manager.py#L165-L169) as follows and share the result?
```python
def _sort(self, lines):
    for score in lines:
        print(score)
        print(score.split())
    scores = [float(score.split()[1]) for score in lines]
    lines = [line for _, line in sorted(zip(scores, lines), reverse=self.is_descending)]

    return lines
```

**Comment by wgp666** [comment]
> Will you change [this function](https://github.com/codeslake/PVDNet/blob/main/ckpt_manager.py#L165-L169) as follows and share the result?
> 
> ```python
> def _sort(self, lines):
>     for score in lines:
>         print(score)
>         print(score.split())
>     scores = [float(score.split()[1]) for score in lines]
>     lines = [line for _, line in sorted(zip(scores, lines), reverse=self.is_descending)]
> 
>     return lines
> ```

![image](https://user-images.githubusercontent.com/89969997/163741063-c86dbdec-ccf4-4cd4-b0bf-3dad7bbc3c1b.png)

**Comment by codeslake** [comment]
Try this:
```python
def _sort(self, lines):
    scores = [float(score.split()[1]) for score in lines if len(score)>1]
    lines = [line for _, line in sorted(zip(scores, lines), reverse=self.is_descending)]

    return lines
```

**Comment by codeslake** [comment]
There should be one line at the point of the error. Can you change the [save function](https://github.com/codeslake/PVDNet/blob/main/ckpt_manager.py#L101-L138) in `ckpt_manager.py` as follows and share the result?

```python
    def save(self, network, state, epoch, score):
        if type(epoch) == str:
            file_name = self.model_name + '_' + epoch + '.pytorch'
        else:
            file_name = self.model_name + '_' + '{:05d}'.format(epoch) + '.pytorch'
        save_path = os.path.join(self.root_dir_ckpt, file_name)
        torch.save(network.state_dict(), save_path)

        save_path = os.path.join(self.root_dir_state, file_name)
        torch.save(state, save_path)

        # remove the most recently added line
        if os.path.exists(self.ckpt_list):
            print(!!!! 1. exists)
            with open(self.ckpt_list, 'r') as file:
                lines = file.read().splitlines()
                line_to_remove  = lines[-1]
                if line_to_remove not in lines[:-1]:
                    os.remove(os.path.join(self.root_dir_ckpt, line_to_remove.split(' ')[0]))
                    os.remove(os.path.join(self.root_dir_state, line_to_remove.split(' ')[0]))
                del(lines[-1])
                file.close()
            with open(self.ckpt_list, 'w') as file:
                for line in lines:
                    file.write(line + os.linesep)
                file.close()

        with open(self.ckpt_list, 'a') as file:
            #line_to_add = file_name + ' ' + str(score) + os.linesep
            line_to_add = file_name
            for s in score:
                line_to_add = line_to_add + ' ' + str(s)
            line_to_add = line_to_add + os.linesep

            file.write(line_to_add) # for the new ckpt
            file.write(line_to_add) # for the most recent ckpt
            file.close()

        self._update_files()
```

**Comment by wgp666** [comment]
> Try this:
> 
> ```python
> def _sort(self, lines):
>     scores = [float(score.split()[1]) for score in lines if len(score)>1]
>     lines = [line for _, line in sorted(zip(scores, lines), reverse=self.is_descending)]
> 
>     return lines
> ```

A new error was reported when I tried this command.
![image](https://user-images.githubusercontent.com/89969997/163743313-339c1888-b11d-400a-b2a7-a98337dc3b71.png)

**Comment by codeslake** [comment]
> > Try this:
> > ```python
> > def _sort(self, lines):
> >     scores = [float(score.split()[1]) for score in lines if len(score)>1]
> >     lines = [line for _, line in sorted(zip(scores, lines), reverse=self.is_descending)]
> > 
> >     return lines
> > ```
> 
> A new error was reported when I tried this command. ![image](https://user-images.githubusercontent.com/89969997/163743313-339c1888-b11d-400a-b2a7-a98337dc3b71.png)

I've never seen this error before, and I am not sure if I can help with this error, as I've never tried this code in Windows. Which pytorch version are you using? Is there GPU available in your PC?

**Comment by wgp666** [comment]
> 

pytorch = 1.8.0
I have a GPU on my PC
I was able to run this code in Ubuntu before. But for some reason my Ubuntu system crashed and I reinstalled a windows system and tried to run the code again and I had this problem. Maybe I should consider reinstalling an Ubuntu system.

**Comment by codeslake** [comment]
Yeah, the environment should work in Ubuntu without a problem. Please try the code in Ubuntu!
