### ISSUE TITLE
Some questions in the test

### ISSUE THREAD

**Issue by liaolianye666** [codeslake/PVDNet#8]
![image](https://user-images.githubusercontent.com/98524307/168425615-c85fb66a-42a4-4a31-a609-d0795a4389bf.png)

Hello, I am using MATLAB to test its performance and set the path, but it is not running

**Comment by codeslake** [comment]
Hi,
Is your dataset placed as described in [here](https://github.com/codeslake/PVDNet/tree/main/evaluation)?

**Comment by liaolianye666** [comment]
The path of the dataset is correct

**Comment by codeslake** [comment]
Change [this line](https://github.com/codeslake/PVDNet/blob/main/evaluation/evaluation.m#L28) as the following, and report the error, please.
```
for j = 2:num
```

**Comment by liaolianye666** [comment]
run_evaluation
Parallel pool using the 'local' profile is shutting down.
Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 4).
PSNR (Koehler): NaN, SSIM (Koehler): NaN

**Comment by codeslake** [comment]
add following line after [here](https://github.com/codeslake/PVDNet/blob/main/evaluation/evaluation.m#L35) and [here](https://github.com/codeslake/PVDNet/blob/main/evaluation/evaluation.m#L40), and share the error please.
```
GT = imread(fullfile(frame_path_GT(GT_idx).folder, frame_path_GT(GT_idx).name));
size(GT)

...

input = imread(fullfile(frame_path_result(j).folder, frame_path_result(j).name));
size(input)
```

**Comment by liaolianye666** [comment]
It's the same problem.

run_evaluation
Parallel pool using the 'local' profile is shutting down.
Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 4).
PSNR (Koehler): NaN, SSIM (Koehler): NaN

**Comment by codeslake** [comment]
It doesn't make sense. Something should be printed out.
Are you sure that you changed [`parfor`](https://github.com/codeslake/PVDNet/blob/main/evaluation/evaluation.m#L28) to `for`?

Let's comment [these lines](https://github.com/codeslake/PVDNet/blob/main/evaluation/run_evaluation.m#L10).

**Comment by liaolianye666** [comment]
Yes, I have changed it, but it is the same every time. Thank you for your patient answer

**Comment by codeslake** [comment]
No worries.



Put the following lines in [here](https://github.com/codeslake/PVDNet/blob/main/evaluation/evaluation.m#L9) and share the result, please. Do not put semicolons after each line.
```
length(folder_gt)
length(video_paths)
```

**Comment by liaolianye666** [comment]
run_evaluation
Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 4).

ans =

    35


ans =

    10

PSNR (Koehler): NaN, SSIM (Koehler): NaN>>

**Comment by codeslake** [comment]
> add following line after [here](https://github.com/codeslake/PVDNet/blob/main/evaluation/evaluation.m#L35) and [here](https://github.com/codeslake/PVDNet/blob/main/evaluation/evaluation.m#L40), and share the error please.
> 
> ```
> GT = imread(fullfile(frame_path_GT(GT_idx).folder, frame_path_GT(GT_idx).name));
> size(GT)
> 
> ...
> 
> input = imread(fullfile(frame_path_result(j).folder, frame_path_result(j).name));
> size(input)
> ```

Do you have semicolons after `size(..)`? If you do, would you remove them and share the result?

**Comment by codeslake** [comment]
Put the following lines in [here](https://github.com/codeslake/PVDNet/blob/main/evaluation/evaluation.m#L26) and share the result, please. Do not put semicolons after each line.

```
length(frame_path_GT)
length(frame_path_result)
```

**Comment by liaolianye666** [comment]
run_evaluation
Parallel pool using the 'local' profile is shutting down.
Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 4).
ans =
    35
ans =
    10
ans =
   100
ans =
     0
ans =
   100
ans =
     0
ans =
   100
ans =
     0
ans =
   100
ans =
     0
ans =
   100
ans =
     0
ans =
   100
ans =
     0
ans =
   100
ans =
     0
ans =
   100
ans =
     0
ans =

   100


ans =

     0


ans =

   100


ans =

     0

PSNR (Koehler): NaN, SSIM (Koehler): NaN

**Comment by liaolianye666** [comment]
run_evaluation
Parallel pool using the 'local' profile is shutting down.
Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 4).

ans =

    35


ans =

    10


ans =

   100


ans =

     0


ans =

   100


ans =

     0


ans =

   100


ans =

     0


ans =

   100


ans =

     0


ans =

   100


ans =

     0


ans =

   100


ans =

     0


ans =

   100


ans =

     0


ans =

   100


ans =

     0


ans =

   100


ans =

     0


ans =

   100


ans =

     0

PSNR (Koehler): NaN, SSIM (Koehler): NaN

**Comment by codeslake** [comment]
Oh, I see. 
You have to modify [this line](https://github.com/codeslake/PVDNet/blob/main/evaluation/run_evaluation.m#L23) to give a proper output path.
You currently gave only `'PVDNet_DVD'`. Add the path up to `.../png/output`

**Comment by liaolianye666** [comment]
Oh，Thank you very much, I run successfully
