### ISSUE TITLE
Hello! It's my great honor to git your code on github, which is related to video deblurring. Because I am a beginner, I encountered the following problems when running your code. I want to ask you. Could you send me your profile? Thank you very much for your contribution.what  can i do?

### ISSUE THREAD

**Issue by huchunjun425** [codeslake/PVDNet#9]
![image](https://user-images.githubusercontent.com/103866259/197193851-39eb9c3d-1dc2-4ceb-8b9b-76985c510e51.png)

**Comment by codeslake** [comment]
Hi, would you leave the command that you typed in the terminal to run the codes?

**Comment by huchunjun425** [comment]
thkans!
i just run this command:
# single GPU (with DataParallel) example
CUDA_VISIBLE_DEVICES=0 python -B run.py \
            ... \
            -ss

**Comment by codeslake** [comment]
''...'' means the omitted options.

Try the following:
```
CUDA_VISIBLE_DEVICES=0 python -B run.py \
            --is_train \
            --mode PVDNet_DVD \
            --config config_PVDNet \
            --trainer trainer \
            --data DVD \
            -LRS CA \
            -b 2 \
            -th 8 \
            -dl \
            -ss \
            -dist
```

**Comment by huchunjun425** [comment]
ok，i got it.thank you very much. after run the command above，but a new issue  has arisen. what can i do for it? i just run this code in a single GPU,which has a 3050 graphics card.
![image](https://user-images.githubusercontent.com/103866259/197196150-f2a902a0-85f7-41e3-981d-a4f9e604478f.png)

**Comment by codeslake** [comment]
Did you change [data_offset](https://github.com/codeslake/PVDNet/blob/main/configs/config.py#L41)?

**Comment by huchunjun425** [comment]
THANKS!,i just change these two command. i did not find a&nbsp;Folder, called '/data1/junyonglee/video_ deblur'，so i change it.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junyong ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 晚上8:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [codeslake/PVDNet] Hello! It&#39;s my great honor to git your code on github, which is related to video deblurring. Because I am a beginner, I encountered the following problems when running your code. I want to ask you. Could you send me your profile? Thank you very much for your contribution.what  can i do? (Issue #9)





 
Did you change data_offset?

**Comment by codeslake** [comment]
Did you change it to the root path for the dataset?

**Comment by huchunjun425** [comment]
THANKS!,i just change these two command. i did not find a Folder, called '/data1/junyonglee/video_ deblur'，so i change it.
![image](https://user-images.githubusercontent.com/103866259/197198577-010f08d0-463e-4cf9-a25d-ee40911160af.png)

**Comment by codeslake** [comment]
Cool, do you encounter any errors now?

**Comment by huchunjun425** [comment]
yes, As I said before, when I run your command, an error is displayed:



Here I want to ask you what is the meaning of "config. data_offset" in the config.py file in your code? Is it just a folder? You still need to follow the same settings. I have not set the dataset folder, only DATASET_ ROOT




best,




huchunjun




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junyong ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 晚上8:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [codeslake/PVDNet] Hello! It&#39;s my great honor to git your code on github, which is related to video deblurring. Because I am a beginner, I encountered the following problems when running your code. I want to ask you. Could you send me your profile? Thank you very much for your contribution.what  can i do? (Issue #9)





 
Cool, do you encounter any errors now?

**Comment by codeslake** [comment]
It is the root path for the dataset. You need to download and unzip datasets.
Refer [here](https://github.com/codeslake/PVDNet#2-datasets) please.

**Comment by huchunjun425** [comment]
May I ask which country you are from? Can you add your contact information? I want to learn more from you.I have modified it according to the read.me file




so,importantly, what can do for this issue? Thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junyong ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 晚上8:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [codeslake/PVDNet] Hello! It&#39;s my great honor to git your code on github, which is related to video deblurring. Because I am a beginner, I encountered the following problems when running your code. I want to ask you. Could you send me your profile? Thank you very much for your contribution.what  can i do? (Issue #9)





 
It is the root path for the dataset. You need to download and unzip datasets.
 Refer here please.

**Comment by codeslake** [comment]
> May I ask which country you are from? Can you add your contact information? I want to learn more from you.I have modified it according to the read.me file

I'm from Korea. If it is about the code, I prefer using the issue page here. If it is not, contact me using my email (junyonglee@postech.ac.kr).

> so,importantly, what can do for this issue? Thanks.

Sorry, I didn't get what you meant.

**Comment by huchunjun425** [comment]
As shown in the picture, when I run a command and encounter such problems, how do I need to change the code? Thank you for your answer




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junyong ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 晚上9:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [codeslake/PVDNet] Hello! It&#39;s my great honor to git your code on github, which is related to video deblurring. Because I am a beginner, I encountered the following problems when running your code. I want to ask you. Could you send me your profile? Thank you very much for your contribution.what  can i do? (Issue #9)





  
May I ask which country you are from? Can you add your contact information? I want to learn more from you.I have modified it according to the read.me file
  
I'm from Korea. If it is about the code, I prefer using the issue page here. If it is not, contact me using my email ***@***.***).
  
so,importantly, what can do for this issue? Thanks.
  
Sorry, I didn't get what you meant.

**Comment by codeslake** [comment]
Where did you unzip your dataset?
Set [data_offset](https://github.com/codeslake/PVDNet/blob/main/configs/config.py#L42) to the root directory of the unzipped dataset.

**Comment by huchunjun425** [comment]
![image](https://user-images.githubusercontent.com/103866259/197204545-7da8c5b8-4f87-4960-b59d-01d8f7d8621c.png)
i just do it ,but  i also meet this issue.thanks.

**Comment by codeslake** [comment]
Where did you unzip your dataset?

**Comment by huchunjun425** [comment]
In this file named DATASET_ ROOT，Decompress dataset .








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junyong ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 晚上9:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [codeslake/PVDNet] Hello! It&#39;s my great honor to git your code on github, which is related to video deblurring. Because I am a beginner, I encountered the following problems when running your code. I want to ask you. Could you send me your profile? Thank you very much for your contribution.what  can i do? (Issue #9)





 
Where did you unzip your dataset?

**Comment by codeslake** [comment]
Can you write down the absolute path for the `train_DVD` folder?
Is it in `E:/code/python/PVDNet/DATASET_ROOT`?
If it is, change [data_offset](https://github.com/codeslake/PVDNet/blob/main/configs/config.py#L42) to `E:/code/python/PVDNet/DATASET_ROOT`

**Comment by codeslake** [comment]
Change [data_offset](https://github.com/codeslake/PVDNet/blob/main/configs/config.py#L42) to 'E:/code/python/PVDNet/dataset'.

**Comment by huchunjun425** [comment]
![image](https://user-images.githubusercontent.com/103866259/197207108-eb11f5be-9591-45ab-9cf3-6b68cb9325ec.png)
Thank you for your answer. I have modified it according to your requirements, but there are still problems, as shown in the figure. Thank you very much for your answer. I will look at your code tomorrow. The code error displays: "ZeroDivisionError: division by zero

**Comment by codeslake** [comment]
Would you try just `datasets`?
